# Generated by Django 4.0.5 on 2022-06-13 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionbank',
            name='marks',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='questionbank',
            name='ques',
            field=models.TextField(default='sample question'),
        ),
        migrations.AddField(
            model_name='questionbank',
            name='subj',
            field=models.CharField(default='CSE', max_length=20),
        ),
        migrations.AlterField(
            model_name='questionbank',
            name='chapter_number',
            field=models.IntegerField(default=0),
        ),
    ]
